sudo: required
dist: trusty
language: python

python:
 - 3.5
 - 3.6

env:
  matrix:
   - DJANGO_VERSION=1.10.8
   - DJANGO_VERSION=1.11.13
   - DJANGO_VERSION=2.0.5

install:
 - sudo apt-get update
 - ./install.sh
 - ./env/bin/pip install -U django==$DJANGO_VERSION
 - ./env/bin/pip install coverage
 - pip install flake8==3.5.0
 - ./env/bin/python ./manage.py collectstatic --noinput

before_script:
 - flake8
 - ./env/bin/pip freeze

script:
 - ./env/bin/python ./manage.py test
 - ./env/bin/coverage run --include="mapentity/*" manage.py test

after_success:
 - pip install coveralls
 - coveralls
